# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ipmon < Formula
  desc "zero dependency ip address monitoring"
  homepage "https://github.com/alxsad/ipmon"
  version "1.0.2"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/alxsad/ipmon/releases/download/v1.0.2/ipmon_Darwin_arm64.tar.gz"
      sha256 "8f3884e0fab083592e942a152df2c14dd0a109a7d1ff972dcf55626c3e004e28"

      def install
        bin.install "ipmon"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/alxsad/ipmon/releases/download/v1.0.2/ipmon_Darwin_x86_64.tar.gz"
      sha256 "47e5386f9a2e906e5978a0410b4d261960d9748e99fe7c0767a36a09d5ec1157"

      def install
        bin.install "ipmon"
      end
    end
  end
end
