# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ipmon < Formula
  desc "zero dependency ip address monitoring"
  homepage "https://github.com/alxsad/ipmon"
  version "1.0.3"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/alxsad/ipmon/releases/download/v1.0.3/ipmon_Darwin_arm64.tar.gz"
      sha256 "c5b670458c69031113eb44c3c9bbae3d2cf2926b494b7c834c4a3a6904dd46d5"

      def install
        bin.install "ipmon"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/alxsad/ipmon/releases/download/v1.0.3/ipmon_Darwin_x86_64.tar.gz"
      sha256 "70c2f01a2ffbd9894fd7511422026b952b2ae0d6b53155a9bf1f8f74ed51f390"

      def install
        bin.install "ipmon"
      end
    end
  end
end
